

# NumPy Kütüphanesi Temel Fonksiyonları ve Uygulamaları 

## İçerik

 ### 1. *NumPy Kütüphanesi Nedir, Nasıl Yüklenir?*
 ### 2. *NumPy Array (Dizi) Yapısı*
     * Dizi Oluşturma 
     * Rastgele (Random) Dizi Oluşturma
     * Dizi Elemanlarına Erişim
     * Dizi Özellikleri ve Operatörleri 
     * Alt-dizi Oluşturma
     * Dizileri Yeniden Boyutlandırma
     
     
 ### 3. *Matematiksel İşlemler*
     * Transpoz İşlemi
     * Matrisin Tersini Bulma
     * Operatörler
     
     
 ### 4. *Yararlanılan Kaynaklar*


## 1. **NumPy Kütüphanesi Nedir, Nasıl Yüklenir?** ##

    NumPy, bilimsel hesaplamalar için kullanılan temel bir Python kütüphanesidir.   
    NumPy kütüphanesini kullanmak için pip veya anaconda ile yükleme işlemi yapılır:
    
~~~
$ pip install numpy
~~~
veya anaconda üzerinde:

~~~
$ conda install numpy
~~~

## 2. **NumPy Array (Dizi) Yapısı**

    Öncelikle yüklü NumPy paketini kullanmak için import işlemini gerçekleştirmeliyiz (Tanımlayacağımız 'np' ile kütüphane fonksiyonlarını çağıracağız.) : 

In [144]:
import numpy as np

Numpy Array, en sık kullanılan Numpy fonksiyonlarındandır. Veri biliminde sıkça kullanılan Numpy kütüphanesinin ayırt edici özelliklerinden birisi Numpy Array'ler ile element-wise hesaplamaların gerçekleştirilebilmesidir. ( Element-wise işlemlerde, konumsal olarak karşılık gelen değerler birleştirilerek yeni bir vektör oluşturulur.)

### ***Dizi Oluşturma*** ###
    - Öncelikle dizi tanımlayarak başlayalım:  

In [145]:
dizi_a = np.array([1,2,3])            ##Bir-boyutlu dizi -1d Array-
dizi_b = np.array([(1,2,3),(4,5,6)])  ##İki-boyutlu dizi -2d Array-

print("1. dizi: "+str(dizi_a)+ "\n"+ "2. dizi: "+str(dizi_b))

1. dizi: [1 2 3]
2. dizi: [[1 2 3]
 [4 5 6]]


Dizileri önceden belirli aralıklarla da oluşturabiliriz. ***arange*** fonksiyonu; sırasıyla başlangıç, bitiş ve adım aralığını 
parametre olarak alıp bitiş noktasının dahil olmadığı bir dizi oluşturur. ***linspace*** başlangıç ve bitiş değerleri arasındaki 
istenilen sayıda eş aralıklı değer türetir. arange'ten farklı olarak linspace'te adım aralığı değil örnek sayısı parametre 
olarak girilir ve bitiş noktası da türetilen değerler içindedir. 



In [146]:
print("arrange ile oluşturulan dizi: "+str(np.arange(1,10,1)))

print("\nlinspace ile oluşturulan dizi: "+str(np.linspace(1,10,3)))

arrange ile oluşturulan dizi: [1 2 3 4 5 6 7 8 9]

linspace ile oluşturulan dizi: [  1.    5.5  10. ]


### ***Random Dizi Oluşturma*** ###

In [147]:
# Dizi tanımlarken sıkça random fonksiyonu kullanılır:
np.random.seed(0)  # seed -> tekrarlanabilirlik için

x1 = np.random.randint(10, size=6)  # Bir-boyutlu dizi- 1d array
x2 = np.random.randint(10, size=(3, 4))  # İki-boyutlu dizi - 2d array
x3 = np.random.randint(10, size=(3, 4, 5))  # Üç-boyutlu dizi - 3d array

print("x1: "+str(x1)+"\n\nx2: "+str(x2)+"\n\nx3: "+str(x3))

x1: [5 0 3 3 7 9]

x2: [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

x3: [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [148]:
# Bir başka yöntem:
print(np.random.rand(3,2))  # random değerler ile 3*2 boyuta sahip bir dizi oluşturur

[[ 0.65279032  0.63505887]
 [ 0.99529957  0.58185033]
 [ 0.41436859  0.4746975 ]]


### *** Dizi Elemanlarına Erişim *** ###

Dizi yapısında axis değerleri satır ve sütunu ifade eder, yani:
    - "axis = 0" satırı
    - "axis = 1" sütunu ifade etmektedir. 

Bir dizi oluşturalım ve elemanlarına nasıl erişebileceğimizi görelim.

**Bir-boyutlu dizide elemanlara erişim:**

In [149]:
TekBoyutluDizi = np.array([22,48,17,25,36,20])
print(TekBoyutluDizi)

# 3. elemana erişim
print(TekBoyutluDizi[3]) 

# Dizinin elemanlarına sondan başa (ters sırayla) ulaşmak için negatif değerler kullanırız, örneğin son elemana ulaşmak için:
print(TekBoyutluDizi[-1])

# veya sondan üçüncü eleman için:

print(TekBoyutluDizi[-3])  

[22 48 17 25 36 20]
25
20
25


**Çok-boyutlu dizide elemanlara erişim:**

In [150]:
multiDizi = np.array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

print(multiDizi)

# 2. satır 1.sütun elemana erişim:
print(multiDizi[2,1])

# 0. satır -1. sütun (son sütun) elemanına erişim:
print(multiDizi[0,-1])


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
6
4


*Erişilen indise istenen sayı ataması gerçekleştirilebilir:*

In [151]:
multiDizi[0,0]= 9
print(multiDizi)

[[9 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


*NumPy dizilerinin sabit bir tipi vardır. Bu nedenle örneğin, bir tam sayı dizisine kayan noktalı (float) bir değer girmeyi 
denerseniz, ondalık kısım kesilir.*

In [152]:
multiDizi[0,0] = 3.14159  
print(multiDizi)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


### *** Dizi Özellikleri ve Operatörleri *** ###

In [153]:
# Dizi boyutunu görüntüleme -> array.shape

print(multiDizi.shape)

# Dizi uzunluğunu görüntüleme -> len(array)  satır sayısı uzunluğa eşittir

print(len(multiDizi))

# Dizi eleman sayısını görüntüleme -> array.size

print(multiDizi.size)

# Dizi elemanlarının veri tipini görüntüleme -> array.dtype

print(multiDizi.dtype)

# Diziyi kopyalama

copyD = multiDizi.copy()
print(copyD)


(3, 4)
3
12
int32
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [154]:
# Dizi sıralama -> array.sort()

y = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
y.sort()

print(y)

# Diziye eleman ekleme işlemi -> np.append(a,b)

a = np.array([(1, 2, 3),(4, 5, 6)])
b = np.append(a, [(7, 8, 9)])

print(b)

# İstenilen satır veya sütuna eleman ekleme işlemi -> np.insert(array, 1, 2, axis) (axis=0 satır)

c= np.insert(b,3,4,0)  # b dizisinin 3.indisine 4 rakamını ekler
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 4 5 6 7 8 9]


### ***Alt-dizi Oluşturma*** ###

In [155]:
# -> np.array_split(array, number of sub-arrays)

aSplit = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(np.array_split(aSplit,3))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


### ***Dizileri Yeniden Boyutlandırma*** ###

In [156]:
# Diziyi yeniden boyutlandırma -> np.resize((2,4))  -index sırasına göre yeniden boyutlandırma yapar

a = np.array([[0, 1],
       [2, 3],
       [4, 5]])

print("1.örnek: "+str( np.reshape(a, (2, 3)))+ "\n" )


# -> np.reshape(a, 6)

a = np.array([[1,2,3], [4,5,6]])

print("2.örnek: "+str(np.reshape(a,6)) )

1.örnek: [[0 1 2]
 [3 4 5]]

2.örnek: [1 2 3 4 5 6]


## 3. **Matematiksel İşlemler**

### ***Transpoz İşlemi***###


In [157]:
# Dizinin transpozunu alma işlemi -> array = np.transpose(other)

Dizi= np.array([[14,21,1,89],[23,12,0,4],[8,23,11,0]])
print(str(Dizi)+"\n")

tDizi = np.transpose(Dizi)
print(tDizi)

# veya -> array.T

print("\n"+str(tDizi.T))



[[14 21  1 89]
 [23 12  0  4]
 [ 8 23 11  0]]

[[14 23  8]
 [21 12 23]
 [ 1  0 11]
 [89  4  0]]

[[14 21  1 89]
 [23 12  0  4]
 [ 8 23 11  0]]


### ***Matrisin Tersini Bulma*** ###

In [158]:
# -> inverse = np.linalg.inv(matrix)

Matris = np.array([[3,1],[2,4]])
print("matris: "+str(Matris)+ "\n")
iMatris = np.linalg.inv(Matris)

print("Matrisin tersi: "+str(iMatris))

matris: [[3 1]
 [2 4]]

Matrisin tersi: [[ 0.4 -0.1]
 [-0.2  0.3]]


### *** Operatörler *** ###

- NumPy Array operatörleri element-wise işlem yaparlar.

In [159]:
# Toplama işlemi -> np.add(x,y)

a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(np.add(a, b))



[[2 4 6]
 [5 7 9]]


In [160]:
# Çıkarma işlemi -> np.substract(x,y)

a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(np.subtract(a, b))


[[ 0  0  0]
 [-3 -3 -3]]


In [161]:
# Bölme işlemi -> np.divide(x,y)

a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(np.divide(a, b))

[[ 1.    1.    1.  ]
 [ 0.25  0.4   0.5 ]]


In [162]:
# Çarpma işlemi -> np.multiply(x,y)

a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(np.multiply(a, b))

# Kök alma işlemi -> np.sqrt(x)

print("\n"+str(np.sqrt(b)))

[[ 1  4  9]
 [ 4 10 18]]

[[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]]


In [163]:
a = np.array([1, 7, 3])
b = np.array([(1, 4, 10), (24, 5, 6)])
c= np.array([90, 0, 180])

# np.sin(x)

print(str(np.sin(c))+"\n")

#np.cos(x)

print(str(np.cos(c))+"\n")

# logaritma hesaplama -> np.log(x)

print(np.log(b))


[ 0.89399666  0.         -0.80115264]

[-0.44807362  1.         -0.59846007]

[[ 0.          1.38629436  2.30258509]
 [ 3.17805383  1.60943791  1.79175947]]


In [164]:
# Matris-vektör çarpımı için dot fonksiyonu tanımlanmıştır ->  np.dot(x,y)

x = np.array([(1, 4, 10), (24, 5, 6),(2, 11, 2)])   # 3x3
y = np.array([4,2,6])                               # 1x3

print(str(np.dot(x,y)))                             # sonuc ->1x3

[ 72 142  42]


In [165]:
# Karşılaştırma Operatörü  -> np.array_equal(x,y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
c = z < 6
print(c)


[ True  True  True  True  True False False False False False]


In [176]:
# İstatistik İşlemleri

# ortalama -> np.mean(array)
x = np.array([(2, 11, 2)])

print("Ortalama: "+str(np.mean(x))+"\n")


# medyan -> np.median(array)

print("Medyan: "+str(np.median(x))+"\n")

# Korelasyon katsayısı -> array.corrcoef()
a = np.array([1, 1, 2, 5, 8, 10, 11, 12])

corArray= np.corrcoef(x)
print("Korelasyon: "+str(corArray)+"\n")

# Standart Sapma -> np.std(array)

print("Standart Sapma: "+str(np.std(a)))

Ortalama: 5.0

Medyan: 2.0

Korelasyon: 1.0

Standart Sapma: 4.29389100933


>## 4. **Yararlanılan Kaynaklar: ** ##

> **Github**: 
    -[  juliangaal/python-cheat-sheet](github.com/juliangaal/python-cheat-sheet)
    -[jakevdp/PythonDataScienceHandbook](github.com/jakevdp/PythonDataScienceHandbook)
> 
  **Diğer:**:
    -[pythondersleri.com](http://www.pythondersleri.com)
    -[spicy.org/numpy](https://docs.scipy.org)